### ISSUE TITLE
Bug in examples/substraction.ml?

### ISSUE THREAD

**Issue by ghost** [ocaml-community/sedlex#31] opened 2015-04-30 22:36 UTC
I try to compile the code

```
let rec token buf =
  match%sedlex buf with
    | white_space -> print_endline "\tWhitespace"; token buf
    | Sub (Chars "ab","b") -> print_endline "a"; token buf
    | (Chars "ab"|"c") -> print_endline "abc"; token buf
    | Intersect ("d", Chars "abd") -> print_endline "d"; token buf
    | eof -> print_endline "\tEnd"
    | any -> print_endline "Other"; token buf
    | _ -> failwith "Internal failure: Reached impossible place"


let () =
  let lexbuf = Sedlexing.Utf8.from_string "a b c d e" in
  token lexbuf
```

And it said  `Sedlex: this pattern is not a valid regexp`, which told me the regexp `Sub (Chars "ab","b")` is not valid.

**Comment by Drup** [comment] 2015-05-07 14:43
I can't reproduce, did you changed something ? Can you give details about your setup ?

**Comment by cakeplus** [comment] 2015-05-09 03:09
I also hit this problem with sedlex.1.99.2 installed from OPAM. Reproducing:
```
ocamlfind ocamlc -c -package sedlex -package gen substraction.ml
File "substraction.ml", line 4, characters 6-26:
Sedlex: this pattern is not a valid regexp
```

**Comment by neolem** [comment] 2016-02-25 01:01
I am facing similar issue. It seems we get this issue when using packages from opam and using 'ocamlfind'. If we build sedlex in our own machine then we can build okay. Maybe this has something to do with the way the opam package is compiled?

**Comment by neolem** [comment] 2016-02-25 01:20
Yup, I can reproduce the error. Change `Makefile` for `subtraction` target to below,

```
subtraction$(EXE): subtraction.ml
	ocamlfind ocamlc -package gen -ppx "$HOME/.opam/4.02.3/lib/sedlex/ppx_sedlex$(EXE)" -I $HOME/.opam/4.02.3/lib/sedlex -o subtraction$(EXE) -linkpkg sedlexing.cma subtraction.ml
```
You get the error as below,
```
File "subtraction.ml", line 4, characters 6-26:
Sedlex: this pattern is not a valid regexp
Makefile:22: recipe for target 'subtraction' failed
make: *** [subtraction] Error 2
```

**Comment by Drup** [comment] 2016-02-25 17:02
Pretty sure it's because you are using the stable version and not the dev version.

**Comment by hhugo** [comment] 2023-02-17 14:06
Should likely be closed.

**Comment by hhugo** [comment] 2023-02-17 16:37
@toots, what do you think of closing this one ?

**Comment by toots** [comment] 2023-02-17 16:39
Looks like it. Anyone can re-open/resubmit if it sill occurs.

**Closed by toots** 2023-02-17 16:39 UTC
